// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DigiDocs.Models;

public partial class Diagnosis
{
    public int DiagnosisId { get; set; }

    public string PatientDiagnosis { get; set; }

    public string PatientRegInvestigation { get; set; }

    public int PatientId { get; set; }

    public int ExaminationId { get; set; }

    public int? CreatedById { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public DateTime LastModifiedDateTime { get; set; }

    public int? LastModifiedById { get; set; }

    public virtual Examination Examination { get; set; }

    public virtual PatientDatum Patient { get; set; }
}