// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DigiDocs.Models;

public partial class DigidocsContext : DbContext
{
    public DigidocsContext(DbContextOptions<DigidocsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Diagnosis> Diagnoses { get; set; }

    public virtual DbSet<Examination> Examinations { get; set; }

    public virtual DbSet<Medicine> Medicines { get; set; }

    public virtual DbSet<PatientDatum> PatientData { get; set; }

    public virtual DbSet<PatientMedication> PatientMedications { get; set; }

    public virtual DbSet<PatientSymptom> PatientSymptoms { get; set; }

    public virtual DbSet<Symptom> Symptoms { get; set; }

    public virtual DbSet<SymptomsCategory> SymptomsCategories { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<PatientQueue> PatientQueues { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PatientQueue>( entity =>
        {
            entity.HasKey(e => e.PatientQueueId).HasName("PK_PatientQueue");
            entity.Property(e => e.Status)
                .IsRequired();

            entity.HasOne(d => d.Patient).WithOne(p => p.PatientQueue)
                .HasForeignKey<PatientQueue>(d => d.PatientId)
                .OnDelete(DeleteBehavior.NoAction)
                .HasConstraintName("FK_PatientQueue_PatientData");
        });

        modelBuilder.Entity<Diagnosis>(entity =>
        {
            entity.HasKey(e => e.DiagnosisId).HasName("PK__Diagnose__0C54CC733224B3AA");

            entity.Property(e => e.CreatedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedDateTime).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Examination).WithMany(p => p.Diagnoses)
                .HasForeignKey(d => d.ExaminationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Diagnoses_Examinations");

            entity.HasOne(d => d.Patient).WithMany(p => p.Diagnoses)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Diagnoses_PatientData");
        });

        modelBuilder.Entity<Examination>(entity =>
        {
            entity.HasKey(e => e.ExaminationId).HasName("PK__Examinat__C4A9242084E14961");

            entity.Property(e => e.CreatedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedDateTime).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Medicine>(entity =>
        {
            entity.HasKey(e => e.MedicineId).HasName("PK__Medicine__4F2128908F21F13A");

            entity.Property(e => e.CreatedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.MedicineName)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<PatientDatum>(entity =>
        {
            entity.HasKey(e => e.PatientId).HasName("PK__PatientD__970EC366E879BB66");

            entity.Property(e => e.CreatedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Paddress)
                .HasMaxLength(500)
                .HasColumnName("PAddress");
            entity.Property(e => e.Page).HasColumnName("PAge");
            entity.Property(e => e.PamountToPay)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("PAmountToPay");
            entity.Property(e => e.PchronicDisease).HasColumnName("PChronicDisease");
            entity.Property(e => e.Pcomplain).HasColumnName("PComplain");
            entity.Property(e => e.Pgender)
                .HasMaxLength(10)
                .HasColumnName("PGender");
            entity.Property(e => e.Pjob)
                .HasMaxLength(100)
                .HasColumnName("PJob");
            entity.Property(e => e.Pname)
                .HasMaxLength(200)
                .HasColumnName("PName");
            entity.Property(e => e.PnextAppointment).HasColumnName("PNextAppointment");
            entity.Property(e => e.PphoneNumber)
                .HasMaxLength(20)
                .HasColumnName("PPhoneNumber");
            //entity.Property(e => e.Ppriority)
            //    .HasMaxLength(50)
            //    .HasColumnName("PPriority");
            //entity.Property(e => e.PserviceType)
            //    .HasMaxLength(100)
            //    .HasColumnName("PServiceType");

            entity.HasOne(d => d.Examination).WithMany(p => p.PatientData)
                .HasForeignKey(d => d.ExaminationId)
                .HasConstraintName("FK_PatientData_Examinations");
        });

        modelBuilder.Entity<PatientMedication>(entity =>
        {
            entity.HasKey(e => e.PatientMedId).HasName("PK__PatientM__47A48821B7EDC2A1");

            entity.Property(e => e.CreatedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Dosage).HasMaxLength(200);
            entity.Property(e => e.Frequency).HasMaxLength(200);
            entity.Property(e => e.LastModifiedDateTime).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Examination).WithMany(p => p.PatientMedications)
                .HasForeignKey(d => d.ExaminationId)
                .HasConstraintName("FK_PatientMedications_Examinations");

            entity.HasOne(d => d.Medicine).WithMany(p => p.PatientMedications)
                .HasForeignKey(d => d.MedicineId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PatientMedications_Medicines");

            entity.HasOne(d => d.Patient).WithMany(p => p.PatientMedications)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PatientMedications_PatientData");
        });

        modelBuilder.Entity<PatientSymptom>(entity =>
        {
            entity.HasKey(e => e.PatientSymId).HasName("PK__PatientS__3A9CC5EDAA737287");

            entity.Property(e => e.CreatedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedDateTime).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Examination).WithMany(p => p.PatientSymptoms)
                .HasForeignKey(d => d.ExaminationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PatientSymptoms_Examinations");

            entity.HasOne(d => d.Patient).WithMany(p => p.PatientSymptoms)
                .HasForeignKey(d => d.PatientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PatientSymptoms_PatientData");

            entity.HasOne(d => d.Symptom).WithMany(p => p.PatientSymptoms)
                .HasForeignKey(d => d.SymptomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PatientSymptoms_Symptoms");
        });

        modelBuilder.Entity<Symptom>(entity =>
        {
            entity.HasKey(e => e.SymptomId).HasName("PK__Symptoms__D26ED896AA7D1E06");

            entity.Property(e => e.CreatedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.SymptomName)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.SymptomsCategory).WithMany(p => p.Symptoms)
                .HasForeignKey(d => d.SymptomsCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Symptoms_SymptomsCategories");
        });

        modelBuilder.Entity<SymptomsCategory>(entity =>
        {
            entity.HasKey(e => e.SymptomsCategoryId).HasName("PK__Symptoms__4D23846DFFB73AE9");

            entity.Property(e => e.CreatedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.SymptomsCategoryName)
                .IsRequired()
                .HasMaxLength(200);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}