// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DigiDocs.Models;

public partial class Examination
{
    public int ExaminationId { get; set; }

    public DateTime? StartAt { get; set; }

    public DateTime? EndAt { get; set; }

    public int? CreatedById { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public DateTime LastModifiedDateTime { get; set; }

    public int? LastModifiedById { get; set; }

    public virtual ICollection<Diagnosis> Diagnoses { get; set; } = new List<Diagnosis>();

    public virtual ICollection<PatientDatum> PatientData { get; set; } = new List<PatientDatum>();

    public virtual ICollection<PatientMedication> PatientMedications { get; set; } = new List<PatientMedication>();

    public virtual ICollection<PatientSymptom> PatientSymptoms { get; set; } = new List<PatientSymptom>();
}