// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DigiDocs.Models;

public partial class PatientSymptom
{
    public int PatientSymId { get; set; }

    public int SymptomId { get; set; }

    public int PatientId { get; set; }

    public int ExaminationId { get; set; }

    public int? CreatedById { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public DateTime LastModifiedDateTime { get; set; }

    public int? LastModifiedById { get; set; }

    public virtual Examination Examination { get; set; }

    public virtual PatientDatum Patient { get; set; }

    public virtual Symptom Symptom { get; set; }
}