// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DigiDocs.Models;

public partial class PatientMedication
{
    public int PatientMedId { get; set; }

    public int PatientId { get; set; }

    public int MedicineId { get; set; }

    public string Dosage { get; set; }

    public string Frequency { get; set; }

    public int? ExaminationId { get; set; }

    public int? CreatedById { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public DateTime LastModifiedDateTime { get; set; }

    public int? LastModifiedById { get; set; }

    public virtual Examination Examination { get; set; }

    public virtual Medicine Medicine { get; set; }

    public virtual PatientDatum Patient { get; set; }
}