// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigiDocs.Enums;
using System;
using System.Collections.Generic;

namespace DigiDocs.Models;

public partial class PatientDatum
{
    public int PatientId { get; set; }

    public string Pname { get; set; }

    public int? Page { get; set; }

    public string Pjob { get; set; }

    public string Pgender { get; set; }

    public string Paddress { get; set; }

    public string Pcomplain { get; set; }

    public string PchronicDisease { get; set; }

    public ServiceType PserviceType { get; set; }

    public Priority Ppriority { get; set; }

    public decimal? PamountToPay { get; set; }

    public string PphoneNumber { get; set; }

    public DateTime? PnextAppointment { get; set; }
    public PatientQueue? PatientQueue { get; set; }
    public int? PatientQueueId { get; set; }

    public int? ExaminationId { get; set; }

    public int? CreatedById { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public DateTime LastModifiedDateTime { get; set; }

    public int? LastModifiedById { get; set; }

    public virtual ICollection<Diagnosis> Diagnoses { get; set; } = new List<Diagnosis>();

    public virtual Examination Examination { get; set; }

    public virtual ICollection<PatientMedication> PatientMedications { get; set; } = new List<PatientMedication>();

    public virtual ICollection<PatientSymptom> PatientSymptoms { get; set; } = new List<PatientSymptom>();
}