// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DigiDocs.Models;

public partial class Symptom
{
    public int SymptomId { get; set; }

    public string SymptomName { get; set; }

    public int SymptomsCategoryId { get; set; }

    public int? CreatedById { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public DateTime LastModifiedDateTime { get; set; }

    public int? LastModifiedById { get; set; }

    public virtual ICollection<PatientSymptom> PatientSymptoms { get; set; } = new List<PatientSymptom>();

    public virtual SymptomsCategory SymptomsCategory { get; set; }
}