// <auto-generated />
using System;
using DigiDocs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiDocs.Migrations
{
    [DbContext(typeof(DigidocsContext))]
    [Migration("20251108231924_UserTable")]
    partial class UserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigiDocs.Models.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ExaminationId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PatientDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientRegInvestigation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiagnosisId")
                        .HasName("PK__Diagnose__0C54CC733224B3AA");

                    b.HasIndex("ExaminationId");

                    b.HasIndex("PatientId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("DigiDocs.Models.Examination", b =>
                {
                    b.Property<int>("ExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExaminationId"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ExaminationId")
                        .HasName("PK__Examinat__C4A9242084E14961");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("DigiDocs.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MedicineId")
                        .HasName("PK__Medicine__4F2128908F21F13A");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("DigiDocs.Models.PatientDatum", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ExaminationId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Paddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PAddress");

                    b.Property<int?>("Page")
                        .HasColumnType("int")
                        .HasColumnName("PAge");

                    b.Property<decimal?>("PamountToPay")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PAmountToPay");

                    b.Property<string>("PchronicDisease")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PChronicDisease");

                    b.Property<string>("Pcomplain")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PComplain");

                    b.Property<string>("Pgender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PGender");

                    b.Property<string>("Pjob")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PJob");

                    b.Property<string>("Pname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PName");

                    b.Property<DateTime?>("PnextAppointment")
                        .HasColumnType("datetime2")
                        .HasColumnName("PNextAppointment");

                    b.Property<string>("PphoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PPhoneNumber");

                    b.Property<string>("Ppriority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PPriority");

                    b.Property<string>("PserviceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PServiceType");

                    b.HasKey("PatientId")
                        .HasName("PK__PatientD__970EC366E879BB66");

                    b.HasIndex("ExaminationId");

                    b.ToTable("PatientData");
                });

            modelBuilder.Entity("DigiDocs.Models.PatientMedication", b =>
                {
                    b.Property<int>("PatientMedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientMedId"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Dosage")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ExaminationId")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("PatientMedId")
                        .HasName("PK__PatientM__47A48821B7EDC2A1");

                    b.HasIndex("ExaminationId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientMedications");
                });

            modelBuilder.Entity("DigiDocs.Models.PatientSymptom", b =>
                {
                    b.Property<int>("PatientSymId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientSymId"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ExaminationId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SymptomId")
                        .HasColumnType("int");

                    b.HasKey("PatientSymId")
                        .HasName("PK__PatientS__3A9CC5EDAA737287");

                    b.HasIndex("ExaminationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SymptomId");

                    b.ToTable("PatientSymptoms");
                });

            modelBuilder.Entity("DigiDocs.Models.Symptom", b =>
                {
                    b.Property<int>("SymptomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SymptomId"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SymptomName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SymptomsCategoryId")
                        .HasColumnType("int");

                    b.HasKey("SymptomId")
                        .HasName("PK__Symptoms__D26ED896AA7D1E06");

                    b.HasIndex("SymptomsCategoryId");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("DigiDocs.Models.SymptomsCategory", b =>
                {
                    b.Property<int>("SymptomsCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SymptomsCategoryId"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SymptomsCategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SymptomsCategoryId")
                        .HasName("PK__Symptoms__4D23846DFFB73AE9");

                    b.ToTable("SymptomsCategories");
                });

            modelBuilder.Entity("DigiDocs.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigiDocs.Models.Diagnosis", b =>
                {
                    b.HasOne("DigiDocs.Models.Examination", "Examination")
                        .WithMany("Diagnoses")
                        .HasForeignKey("ExaminationId")
                        .IsRequired()
                        .HasConstraintName("FK_Diagnoses_Examinations");

                    b.HasOne("DigiDocs.Models.PatientDatum", "Patient")
                        .WithMany("Diagnoses")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Diagnoses_PatientData");

                    b.Navigation("Examination");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DigiDocs.Models.PatientDatum", b =>
                {
                    b.HasOne("DigiDocs.Models.Examination", "Examination")
                        .WithMany("PatientData")
                        .HasForeignKey("ExaminationId")
                        .HasConstraintName("FK_PatientData_Examinations");

                    b.Navigation("Examination");
                });

            modelBuilder.Entity("DigiDocs.Models.PatientMedication", b =>
                {
                    b.HasOne("DigiDocs.Models.Examination", "Examination")
                        .WithMany("PatientMedications")
                        .HasForeignKey("ExaminationId")
                        .HasConstraintName("FK_PatientMedications_Examinations");

                    b.HasOne("DigiDocs.Models.Medicine", "Medicine")
                        .WithMany("PatientMedications")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientMedications_Medicines");

                    b.HasOne("DigiDocs.Models.PatientDatum", "Patient")
                        .WithMany("PatientMedications")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientMedications_PatientData");

                    b.Navigation("Examination");

                    b.Navigation("Medicine");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DigiDocs.Models.PatientSymptom", b =>
                {
                    b.HasOne("DigiDocs.Models.Examination", "Examination")
                        .WithMany("PatientSymptoms")
                        .HasForeignKey("ExaminationId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientSymptoms_Examinations");

                    b.HasOne("DigiDocs.Models.PatientDatum", "Patient")
                        .WithMany("PatientSymptoms")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientSymptoms_PatientData");

                    b.HasOne("DigiDocs.Models.Symptom", "Symptom")
                        .WithMany("PatientSymptoms")
                        .HasForeignKey("SymptomId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientSymptoms_Symptoms");

                    b.Navigation("Examination");

                    b.Navigation("Patient");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("DigiDocs.Models.Symptom", b =>
                {
                    b.HasOne("DigiDocs.Models.SymptomsCategory", "SymptomsCategory")
                        .WithMany("Symptoms")
                        .HasForeignKey("SymptomsCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Symptoms_SymptomsCategories");

                    b.Navigation("SymptomsCategory");
                });

            modelBuilder.Entity("DigiDocs.Models.Examination", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("PatientData");

                    b.Navigation("PatientMedications");

                    b.Navigation("PatientSymptoms");
                });

            modelBuilder.Entity("DigiDocs.Models.Medicine", b =>
                {
                    b.Navigation("PatientMedications");
                });

            modelBuilder.Entity("DigiDocs.Models.PatientDatum", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("PatientMedications");

                    b.Navigation("PatientSymptoms");
                });

            modelBuilder.Entity("DigiDocs.Models.Symptom", b =>
                {
                    b.Navigation("PatientSymptoms");
                });

            modelBuilder.Entity("DigiDocs.Models.SymptomsCategory", b =>
                {
                    b.Navigation("Symptoms");
                });
#pragma warning restore 612, 618
        }
    }
}
